### ISSUE TITLE
Please implement relation->way

### ISSUE THREAD

**Issue by chrispickford** [jfirebaugh/leaflet-osm#12]
First up, thanks for creating this plugin, it very nearly does exactly what I'm looking for and will save me tons of time parsing OSM XML structure.

My use case is to display a UK county boundary on a leafletjs map using an OSM layer much like they do on the OSM website, E.g. http://www.openstreetmap.org/relation/81941.

The XML URI for this "relation" is here: http://www.openstreetmap.org/api/0.6/relation/81941

And follows the following structure:

    <osm ...>
      <relation ...>
        <member type="way" ... />
        ...
        <member type="way" ... />
      </relation>
    </osm>

In [leaflet-osm.js:260](https://github.com/jfirebaugh/leaflet-osm/blob/master/leaflet-osm.js#L260) is the comment `// relation-way and relation-relation membership not implemented`.

Please could you look at implementing the above or advise on whether it's on your roadmap?

**Comment by jfirebaugh** [comment]
`L.OSM.getRelations` is only used as an additional condition to determine if nodes are "interesting" and should be individually displayed. If they are members of a relation, they're considered interesting.

If you use the "/full" relation URL for loading the relation data, you'll get the member ways, and `L.OSM.DataLayer#addData` will render them. As an example, the code that osm.org uses is [here](https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/app/assets/javascripts/leaflet.map.js#L191-L244).

**Comment by chrispickford** [comment]
Ideal, thanks for pointing that out!
