### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by idleberg** [jfirebaugh/leaflet-osm#9]
Any chance you could add this to [cdnjs](https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library) and/or [jsDelivr](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md)?

**Comment by jfirebaugh** [comment]
It's available on the Mapbox CDN: https://www.mapbox.com/mapbox.js/plugins/#leaflet-osm
